name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Required for OIDC
      actions: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #- name: Setup Google Cloud SDK
    #  uses: google-github-actions/setup-gcloud@v1
    #  with:
    #    project_id: ${{ secrets.GCP_PROJECT_ID }}
    #    service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Authenticate to Google Cloud
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'tset-10101010'
        workload_identity_provider: 'projects/366703108700/locations/global/workloadIdentityPools/github-test/providers/my-repo'
#       workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

